services:
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: hackaton
      POSTGRES_DB: app
    ports:
      - '5432:5432'
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql
